import { Poppins } from 'next/font/google'
import '../styles/reset.scss';
import '../styles/global.scss';

const poppins = Poppins({weight:['400', '500', '600', '700'], subsets: ['latin']})

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body  className={`${poppins.className}`}>{children}</body>
    </html>
  )
}
